### ISSUE TITLE
How to set default values to mysql functions

### ISSUE THREAD

**Issue by theCrius** [qawemlilo/widget-knex-schema#2]
Just as the subject ask. Let's say I want to set the default to uuid() for example

**Comment by theCrius** [comment]
I totally missed

`test_uuid: {type: 'uuid', nullable: false}`

**Comment by qawemlilo** [comment]
Hi @theCrius , this module is dependent on knex and I don't think that functionality is available: [please see](http://knexjs.org/#Schema-uuid).

**Comment by qawemlilo** [comment]
Ok great 👍

**Comment by theCrius** [comment]
Yes sorry, I had a long day finding some solution for a side project and didn't thought to check on knex first.
However there are plenty of node package that can help fixing this kind of issues so all good :)

Thanks for this package anyway, very simple and straight forward :+1:
